### ISSUE TITLE
Ajax 

### ISSUE THREAD

**Issue by grodrigues** [danielschmitz/react-guia-do-iniciante-codigos#1]
Boa Tarde @danielschmitz , parabéns pela iniciativa e pelo projeto. Não seria interessante fazer o Ajax com o próprio React em vez fazer com o Jquery ?

**Comment by danielschmitz** [comment]
Olá, sim! Na época era um pouco diferente.
Hoje em dia usamos uma biblioteca separada, geralmente o [Axios](https://github.com/axios/axios), para realizar tal tarefa, inclusive com suporte a Promises
